"""empty message

Revision ID: 1023daf33e12
Revises: 2486478353a3
Create Date: 2020-05-19 02:17:19.289697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1023daf33e12'
down_revision = '2486478353a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_artist_item_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venue_item_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_item')
    op.drop_column('Show', 'artist_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_item', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('venue_item', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Show_venue_item_fkey', 'Show', 'Venue', ['venue_item'], ['id'])
    op.create_foreign_key('Show_artist_item_fkey', 'Show', 'Artist', ['artist_item'], ['id'])
    # ### end Alembic commands ###
